name: Call Reusable Workflow
on: push

jobs:
    call-greeting:
        uses: ./.github/workflows/reusable.yml
        with:
            name: "Hari Kammana"
        secrets:
            my_secret: ${{ secrets.MY_SECRET }}
