name: Reusable Workflow
on:
    workflow_call:
        inputs:
            name:
                description: Enter the name
                required: true
                type: string
        secrets:
            my_secret:
                description: The secret to use in this workflow

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting Step
              run: echo "Hi ${{ inputs.name }} Welcome to Reusable Workflow"
            - name: This is my secret
              run: echo "My secret is ${{ secrets.my_secret }}"